site_name: htmy
repo_name: volfpeter/htmy
repo_url: https://github.com/volfpeter/htmy

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths: [.]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - Examples:
      - Examples: examples/index.md
      - examples/snippet-slots-fastapi.md
      - examples/fastapi-htmx-tailwind-daisyui.md
      - examples/markdown.md
      - examples/internationalization.md
  - API Reference:
      - api/core.md
      - Renderer:
          - api/renderer/default.md
          - api/renderer/baseline.md
      - HTML: api/html.md
      - Snippet: api/snippet.md
      - Markdown: api/md.md
      - I18n: api/i18n.md
      - api/utils.md
      - api/typing.md
      - api/etree.md
